# Feature Engineering and Market Metrics

In [2]:
import pandas as pd

In [3]:
date_cols = ["CloseDate", "PurchaseContractDate", "ListingContractDate"]

In [4]:
listings = pd.read_csv("cleaned_listings.csv", parse_dates=date_cols)
sold = pd.read_csv("cleaned_sold.csv", parse_dates=date_cols)

C:\Users\mukun\AppData\Local\Temp\ipykernel_836\709283278.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  listings = pd.read_csv("cleaned_listings.csv", parse_dates=date_cols)
C:\Users\mukun\AppData\Local\Temp\ipykernel_836\709283278.py:2: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sold = pd.read_csv("cleaned_sold.csv", parse_dates=date_cols)

### Calculating Key Metrics for Each Listing in the Datasets

##### Price Ratio for Negotiation Strength

In [5]:
listings["PriceRatio"] = listings["ClosePrice"]/listings["OriginalListPrice"]
sold["PriceRatio"] = sold["ClosePrice"]/sold["OriginalListPrice"]

##### Price/SQR ft to Normalize Prices Across Sizes

In [6]:
listings["PricePerSQRft"] = listings["ClosePrice"]/listings["LivingArea"]
sold["PricePerSQRft"] = sold["ClosePrice"]/sold["LivingArea"]

##### Close to Original Price to Capture Full Price Reduction History

In [7]:
listings["ClosetoOriginalRatio"] = listings["ClosePrice"]/listings["OriginalListPrice"]
sold["ClosetoOriginalRatio"] = sold["ClosePrice"]/sold["OriginalListPrice"]

##### Listing to Contract Days to Measure Time from Listing to Accepted Offer

In [8]:
listings["ListingtoContractDays"] = listings["PurchaseContractDate"] - listings["ListingContractDate"]
sold["ListingtoContractDays"] = sold["PurchaseContractDate"] - sold["ListingContractDate"]

##### Contract to Close Date to Measure Escrow and Closing Period Duration

In [9]:
listings["ContractToCloseDate"] = listings["CloseDate"] - listings["PurchaseContractDate"]
sold["ContractToCloseDate"] = sold["CloseDate"] - sold["PurchaseContractDate"]

### Segment Analysis

Now, I want to understand how the metrics I just calculated compare among different groups of sold listings. This will help me see what trend analysis I want to perform in the future and capture in my Tableau visualizations.

##### Segmenting by Area

In [30]:
sold.groupby("MLSAreaMajor")[["PriceRatio", "PricePerSQRft", "ClosetoOriginalRatio", "ListingtoContractDays", "ContractToCloseDate"]].median().reset_index()

,MLSAreaMajor,PriceRatio,PricePerSQRft,ClosetoOriginalRatio,ListingtoContractDays,ContractToCloseDate
0,"1 - Belmont Shore/Park,Naples,Marina Pac,Bay Hrbr",0.984556,850.159405,0.984556,33 days 00:00:00,30 days 00:00:00
1,101 - North Inglewood,0.995001,512.477021,0.995001,30 days 12:00:00,33 days 00:00:00
2,102 - South Inglewood,0.979983,534.429599,0.979983,29 days 00:00:00,36 days 00:00:00
3,103 - Ladera Heights,0.966128,613.370787,0.966128,44 days 00:00:00,30 days 00:00:00
4,105 - Lennox,1.000000,631.533101,1.000000,39 days 00:00:00,38 days 00:00:00
...,...,...,...,...,...,...
956,YG17 - Ahwahnee,0.956973,233.619764,0.956973,35 days 00:00:00,24 days 00:00:00
957,YG20 - Coarsegold,0.967020,223.870056,0.967020,79 days 00:00:00,31 days 00:00:00
958,YG40 - Bass Lake,0.905292,499.001996,0.905292,117 days 00:00:00,29 days 00:00:00
959,YG50 - North Fork,0.942755,316.365627,0.942755,57 days 12:00:00,27 days 00:00:00
960,YNEZ - Santa Ynez Valley,0.945574,730.410725,0.945574,43 days 12:00:00,30 days 12:00:00

##### Segmenting by Property Sub Type

In [31]:
sold.groupby("PropertySubType")[["PriceRatio", "PricePerSQRft", "ClosetoOriginalRatio", "ListingtoContractDays", "ContractToCloseDate"]].median().reset_index()

,PropertySubType,PriceRatio,PricePerSQRft,ClosetoOriginalRatio,ListingtoContractDays,ContractToCloseDate
0,BoatSlip,0.924863,1575.000000,0.924863,59 days 00:00:00,15 days 00:00:00
1,Cabin,0.923432,280.172414,0.923432,60 days 00:00:00,31 days 00:00:00
2,CoOwnership,0.954358,438.247078,0.954358,36 days 12:00:00,99 days 12:00:00
3,Condominium,0.980966,545.864217,0.980966,32 days 00:00:00,28 days 00:00:00
4,Duplex,0.980952,535.104364,0.980952,30 days 00:00:00,31 days 00:00:00
5,Farm,0.925000,462.500000,0.925000,39 days 00:00:00,24 days 00:00:00
6,Loft,1.000000,569.444444,1.000000,39 days 00:00:00,38 days 00:00:00
7,ManufacturedHome,1.012526,172.916667,1.012526,69 days 00:00:00,60 days 00:00:00
8,ManufacturedOnLand,0.965451,224.248453,0.965451,48 days 00:00:00,33 days 00:00:00
9,MixedUse,0.917942,464.367816,0.917942,85 days 00:00:00,31 days 00:00:00
10,MobileHome,0.896254,1273.035440,0.896254,116 days 00:00:00,14 days 00:00:00
11,OwnYourOwn,0.935644,632.352941,0.935644,72 days 00:00:00,21 days 00:00:00
12,Quadruplex,0.958333,386.718750,0.958333,25 days 00:00:00,34 days 00:00:00
13,SingleFamilyResidence,1.000000,534.647551,1.000000,22 days 00:00:00,28 days 00:00:00
14,StockCooperative,0.971896,405.213904,0.971896,36 days 12:00:00,46 days 00:00:00
15,Studio,0.922636,675.052411,0.922636,134 days 00:00:00,32 days 00:00:00
16,Timeshare,0.812500,4.483385,0.812500,71 days 12:00:00,20 days 00:00:00
17,Townhouse,0.994953,545.255725,0.994953,23 days 00:00:00,28 days 00:00:00
18,Triplex,0.982250,515.738285,0.982250,45 days 00:00:00,35 days 00:00:00

##### Segmenting by County

In [32]:
sold.groupby("CountyOrParish")[["PriceRatio", "PricePerSQRft", "ClosetoOriginalRatio", "ListingtoContractDays", "ContractToCloseDate"]].median().reset_index()

,CountyOrParish,PriceRatio,PricePerSQRft,ClosetoOriginalRatio,ListingtoContractDays,ContractToCloseDate
0,Alameda,1.026711,696.750903,1.026711,13 days 00:00:00,21 days 00:00:00
1,Amador,0.933744,279.794952,0.933744,56 days 12:00:00,41 days 00:00:00
2,Butte,0.987870,267.028452,0.987870,29 days 00:00:00,30 days 00:00:00
3,Calaveras,0.989790,280.275371,0.989790,20 days 00:00:00,29 days 00:00:00
4,Colusa,1.000000,269.993165,1.000000,6 days 00:00:00,21 days 00:00:00
5,Contra Costa,1.000000,520.705771,1.000000,13 days 00:00:00,22 days 00:00:00
6,El Dorado,0.929900,408.082409,0.929900,55 days 00:00:00,27 days 00:00:00
7,Fresno,0.978100,252.984372,0.978100,37 days 00:00:00,29 days 00:00:00
8,Glenn,0.970265,261.140598,0.970265,29 days 00:00:00,30 days 12:00:00
9,Humboldt,0.877797,147.923009,0.877797,28 days 00:00:00,31 days 12:00:00
10,Imperial,0.972697,214.142287,0.972697,51 days 12:00:00,26 days 12:00:00
11,Inyo,0.909244,268.486352,0.909244,163 days 00:00:00,40 days 00:00:00
12,Kern,0.982801,227.393617,0.982801,37 days 00:00:00,31 days 00:00:00
13,Kings,1.000000,235.010707,1.000000,16 days 00:00:00,28 days 00:00:00
14,Lake,0.947476,208.719520,0.947476,65 days 12:00:00,30 days 00:00:00
15,Lassen,0.816527,109.287752,0.816527,140 days 00:00:00,41 days 12:00:00
16,Los Angeles,0.995009,611.111111,0.995009,26 days 00:00:00,30 days 00:00:00
17,Madera,0.968980,244.817597,0.968980,51 days 12:00:00,30 days 00:00:00
18,Marin,0.971867,774.336283,0.971867,32 days 00:00:00,17 days 00:00:00
19,Mariposa,0.961754,260.386191,0.961754,69 days 00:00:00,30 days 00:00:00
20,Mendocino,0.944730,388.373935,0.944730,67 days 00:00:00,30 days 00:00:00
21,Merced,0.979555,259.036145,0.979555,31 days 00:00:00,30 days 00:00:00
22,Modoc,0.971347,138.310894,0.971347,93 days 00:00:00,69 days 00:00:00
23,Mono,0.942168,604.892640,0.942168,37 days 12:00:00,19 days 12:00:00
24,Monterey,0.980136,572.245017,0.980136,18 days 00:00:00,28 days 00:00:00
25,Napa,0.988572,477.836296,0.988572,40 days 00:00:00,27 days 00:00:00
26,Nevada,1.002993,303.163918,1.002993,28 days 00:00:00,26 days 12:00:00
27,Orange,0.993068,690.505086,0.993068,25 days 00:00:00,29 days 00:00:00
28,Other,0.907384,294.595693,0.907384,173 days 00:00:00,32 days 00:00:00
29,Other State,0.978893,141.373187,0.978893,27 days 00:00:00,24 days 00:00:00
30,Placer,0.981308,343.383585,0.981308,10 days 00:00:00,20 days 00:00:00
31,Plumas,0.965362,304.388736,0.965362,50 days 12:00:00,39 days 00:00:00
32,Riverside,0.981964,323.497093,0.981964,41 days 00:00:00,29 days 00:00:00
33,Sacramento,0.997009,309.704061,0.997009,19 days 00:00:00,24 days 00:00:00
34,San Benito,0.994595,427.170868,0.994595,19 days 00:00:00,29 days 00:00:00
35,San Bernardino,0.992308,329.301223,0.992308,33 days 00:00:00,31 days 00:00:00
36,San Diego,0.994222,590.971560,0.994222,19 days 00:00:00,26 days 00:00:00
37,San Francisco,1.040386,1014.705882,1.040386,13 days 00:00:00,19 days 00:00:00
38,San Joaquin,0.990727,314.298215,0.990727,26 days 00:00:00,28 days 00:00:00
39,San Luis Obispo,0.985504,541.239602,0.985504,27 days 00:00:00,30 days 00:00:00
40,San Mateo,1.028771,1058.476360,1.028771,11 days 00:00:00,21 days 00:00:00
41,Santa Barbara,0.996925,460.649468,0.996925,21 days 00:00:00,30 days 00:00:00
42,Santa Clara,1.017643,944.831959,1.017643,9 days 00:00:00,21 days 00:00:00
43,Santa Cruz,0.985832,731.682813,0.985832,14 days 00:00:00,23 days 00:00:00
44,Shasta,0.976378,251.256281,0.976378,38 days 00:00:00,32 days 00:00:00
45,Siskiyou,0.974269,204.895072,0.974269,48 days 00:00:00,30 days 12:00:00
46,Solano,1.000000,339.631134,1.000000,21 days 12:00:00,25 days 00:00:00
47,Sonoma,1.000000,484.145544,1.000000,13 days 00:00:00,20 days 12:00:00
48,Stanislaus,0.983603,292.635150,0.983603,24 days 00:00:00,28 days 00:00:00
49,Sutter,1.000451,256.158074,1.000451,27 days 00:00:00,26 days 00:00:00
50,Tehama,0.952381,230.894309,0.952381,47 days 00:00:00,32 days 00:00:00
51,Trinity,0.950000,158.906135,0.950000,139 days 00:00:00,60 days 00:00:00
52,Tulare,0.992958,236.472205,0.992958,25 days 12:00:00,30 days 00:00:00
53,Tuolumne,0.973458,259.053889,0.973458,20 days 12:00:00,30 days 00:00:00
54,Ventura,0.990039,518.485122,0.990039,34 days 00:00:00,24 days 00:00:00
55,Yolo,0.994058,285.208213,0.994058,12 days 12:00:00,29 days 12:00:00
56,Yuba,0.965598,228.017481,0.965598,53 days 12:00:00,31 days 00:00:00

##### Segmenting by Listing Office

In [33]:
sold.groupby("ListOfficeName")[["PriceRatio", "PricePerSQRft", "ClosetoOriginalRatio", "ListingtoContractDays", "ContractToCloseDate"]].median().reset_index()

,ListOfficeName,PriceRatio,PricePerSQRft,ClosetoOriginalRatio,ListingtoContractDays,ContractToCloseDate
0,#1 FLAT FEE-LIBERTY REALTY,1.022388,685.000000,1.022388,27 days 00:00:00,25 days 00:00:00
1,#1 Home Sales®,1.078582,280.000000,1.078582,39 days 00:00:00,34 days 00:00:00
2,*,1.046296,643.507973,1.046296,21 days 00:00:00,31 days 00:00:00
3,1 Percent Lists Smart Rate Realty,1.022933,307.434895,1.022933,24 days 00:00:00,29 days 00:00:00
4,1 Realty,1.730002,540.118639,1.730002,43 days 00:00:00,37 days 00:00:00
...,...,...,...,...,...,...
7692,rayrobinson.realtor,0.855519,320.777342,0.855519,76 days 12:00:00,53 days 12:00:00
7693,reGroup Properties,0.942184,434.602649,0.942184,60 days 00:00:00,29 days 00:00:00
7694,reframe,0.997294,648.084985,0.997294,37 days 00:00:00,25 days 12:00:00
7695,smithREgroup,0.862293,763.594523,0.862293,76 days 12:00:00,26 days 12:00:00
7696,zRE Group,1.020408,556.792873,1.020408,21 days 00:00:00,15 days 00:00:00

##### Segmenting by Buyer Office

In [34]:
sold.groupby("BuyerOfficeName")[["PriceRatio", "PricePerSQRft", "ClosetoOriginalRatio", "ListingtoContractDays", "ContractToCloseDate"]].median().reset_index()

,BuyerOfficeName,PriceRatio,PricePerSQRft,ClosetoOriginalRatio,ListingtoContractDays,ContractToCloseDate
0,& Company Real Estate,0.959867,462.184291,0.959867,17 days 12:00:00,26 days 12:00:00
1,*,0.866733,694.221509,0.866733,85 days 00:00:00,48 days 00:00:00
2,1 Realty,1.060510,666.000000,1.060510,33 days 00:00:00,48 days 00:00:00
3,1 Vision Real Estate,1.013793,429.566563,1.013793,53 days 00:00:00,44 days 00:00:00
4,1% LISTING FEE,0.897059,373.774510,0.897059,96 days 00:00:00,19 days 00:00:00
...,...,...,...,...,...,...
8033,reGroup Properties,0.934164,434.602649,0.934164,0 days 00:00:00,29 days 00:00:00
8034,reframe,0.985398,596.935681,0.985398,32 days 00:00:00,26 days 12:00:00
8035,simpliHOM Inc,1.160079,927.598606,1.160079,73 days 00:00:00,22 days 00:00:00
8036,zDefault Office,0.995069,724.138699,0.995069,28 days 12:00:00,24 days 00:00:00
8037,zRE Group,0.994819,563.893210,0.994819,72 days 12:00:00,14 days 12:00:00

### Saving New Datasets with Updated Metric Columns as CSVs

In [37]:
listings.to_csv("listings_with_metrics.csv", index=False)

In [38]:
sold.to_csv("sold_with_metrics.csv", index=False)